FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm

RUN npm install -g @angular/cli@18.2.4
RUN npm install -g create-next-app@14.2.11

WORKDIR /workspaces/software-trends-webframeworks

CMD ["bash"]